//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAreasTareas
    {
        public int id { get; set; }
        public string Area { get; set; }
        public string Tipo_Tarea { get; set; }
        public string Tarea { get; set; }
        public int Dias { get; set; }
        public bool Estado { get; set; }
    }
}
