//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConceptosMedicos
    {
        public int id_Concepto { get; set; }
        public string Doc_Cliente { get; set; }
        public string Fuerza { get; set; }
        public string Tipo_Concepto { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public string Dispensario { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public string Otro_Lugar { get; set; }
        public bool Adjuntar_Documento { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Ruta { get; set; }
        public string Estado_Concepto { get; set; }
        public bool Informar_Cliente { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime Fecha_Cargado { get; set; }
        public System.DateTime Fecha_Modificado { get; set; }
        public string Usuario { get; set; }
    }
}
