//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCiudades
    {
        public int id_Ciudad { get; set; }
        public string Nombre_Ciudad { get; set; }
        public int id_Departamento { get; set; }
    
        public virtual tblDepartamentos tblDepartamentos { get; set; }
    }
}
