//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentosCargados
    {
        public int id_Archivo { get; set; }
        public string doc_cliente { get; set; }
        public string tipo_doc { get; set; }
        public string nombre_archivo { get; set; }
        public string ruta { get; set; }
        public System.DateTime fecha_subido { get; set; }
        public System.DateTime fecha_actualizado { get; set; }
        public bool informar_cliente { get; set; }
        public string usuario { get; set; }
    }
}
