//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNovedadesFamilia
    {
        public int Id_Novedad { get; set; }
        public string Doc_Familiar { get; set; }
        public string Tipo_Novedad { get; set; }
        public string Descripcion { get; set; }
        public bool Adjuntar_Archivo { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Ruta { get; set; }
        public bool Informar_Cliente { get; set; }
        public System.DateTime Fecha_Subido { get; set; }
        public System.DateTime Fecha_Modificado { get; set; }
        public string Usuario { get; set; }
    }
}
