//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistrarSeguimiento
    {
        public int id_Seguimiento { get; set; }
        public int id_Solicitud { get; set; }
        public string Descripcion { get; set; }
        public bool Adjunto { get; set; }
        public string Ruta { get; set; }
        public string Nombre_Archivo { get; set; }
        public bool Notificar_Responsable { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha_Seguimiento { get; set; }
        public string Usuario_Seguimiento { get; set; }
    }
}
