//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoles
    {
        public int Id_Rol { get; set; }
        public string Nombre_Rol { get; set; }
        public int Id_Perfil { get; set; }
        public bool Estado_Rol { get; set; }
    }
}
