//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistrarTareas
    {
        public int id_Solicitud { get; set; }
        public int id_Tarea { get; set; }
        public string Creador { get; set; }
        public string Responsable { get; set; }
        public string Doc_Cliente { get; set; }
        public string Primer_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Descripcion { get; set; }
        public string Prioridad { get; set; }
        public string Estado { get; set; }
        public bool Adjunto { get; set; }
        public string Ruta { get; set; }
        public string Nombre_Archivo { get; set; }
        public bool Notificar_Responsable { get; set; }
        public string Area_Creadora { get; set; }
        public System.DateTime Fecha_Asignado { get; set; }
        public System.DateTime Fecha_Actualizado { get; set; }
    }
}
