//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTelefonosClientes
    {
        public int id_Telefono { get; set; }
        public string Doc_Cliente { get; set; }
        public string Numero_Telefono { get; set; }
        public System.DateTime Fecha_Insertado { get; set; }
        public System.DateTime Fecha_Actualizado { get; set; }
        public string Usuario { get; set; }
    }
}
